export * from "./domains/shared";
export * from "./domains/learning-evidence";
export * from "./domains/assessment";
export * from "./domains/promotion";
export * from "./domains/pedagogical-memory";
export * from "./domains/accessibility";
export * from "./domains/sync";
export * from "./persistence";
export * from "./application";
